apiVersion: v1
kind: ConfigMap
metadata:
  name: office-mgmt-config
  namespace: office-mgmt
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DB_HOST: postgres
  DB_NAME: usersdb
  DB_PORT: "5432"
  DB_USER: usr
