apiVersion: apps/v1
kind: Deployment
metadata:
  name: office-mgmt-api
  namespace: office-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/sonahakobyan/user-mgmt:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "9001"
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: office-mgmt-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: office-mgmt-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: office-mgmt-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: office-mgmt-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: office-mgmt-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: office-mgmt-secret
                  key: DB_PASSWORD
            - name: ConnectionStrings__UsersDb
              value: "Host=$(DB_HOST);Port=$(DB_PORT);Database=$(DB_NAME);Username=$(DB_USER);Password=$(DB_PASSWORD)"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
